const $=id=>document.getElementById(id);
let data=JSON.parse(localStorage.getItem('tripV2')||'{}');
let state={day:0};
data={title:'胡志明 & 富國島',subtitle:'Buon Viaggio · Vietnam Trip',tripName:'',startDate:new Date().toISOString().slice(0,10),days:5,schedules:[],maps:[],budgets:[],places:[],...data};
function save(){localStorage.setItem('tripV2',JSON.stringify(data));render()}
function init(){ $('mainTitle').textContent=data.title; $('subtitle').textContent=data.subtitle; $('tripName').value=data.tripName; $('startDate').value=data.startDate; $('tripDays').value=data.days; render() }
function fmt(d){return new Date(d+'T00:00:00').toLocaleDateString('zh-TW',{month:'short',day:'numeric'})}
function dayDate(i){let d=new Date(data.startDate+'T00:00:00');d.setDate(d.getDate()+i);return d.toISOString().slice(0,10)}
function generateDays(){data.tripName=$('tripName').value;data.startDate=$('startDate').value;data.days=+$('tripDays').value||1;state.day=0;save()}
function render(){ $('mainTitle').textContent=data.title; $('subtitle').textContent=data.subtitle; renderDays(); renderSchedules(); renderMaps(); renderBudgets(); renderPlaces() }
function renderDays(){let html='';for(let i=0;i<data.days;i++){html+=`<button class="day-tab ${i===state.day?'active':''}" onclick="state.day=${i};render()"><small>D${i+1}</small><b>${new Date(dayDate(i)).getDate()}</b><span>${fmt(dayDate(i)).split(' ')[0]}</span></button>`}$('dayTabs').innerHTML=html}
function renderSchedules(){let items=data.schedules.filter(x=>x.day===state.day).sort((a,b)=>a.time.localeCompare(b.time));$('scheduleList').innerHTML=items.length?items.map(x=>`<div class="item"><div class="time">${x.time||'未填時間'}</div><div class="item-title">${x.title}</div><div class="muted">${x.place||''}</div><div>${x.note||''}</div><div class="actions"><button onclick="del('schedules','${x.id}')">刪除</button></div></div>`).join(''):'<div class="empty">今天還沒有行程，點「＋新增」開始塞進旅行寶石吧。</div>'}
function renderMaps(){ $('mapList').innerHTML=data.maps.length?data.maps.map(x=>`<div class="item"><div class="item-title">${x.name}</div><div class="muted">${x.note||''}</div><div class="actions"><button onclick="location.href='https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(x.name)}'">開啟地圖</button><button class="danger" onclick="del('maps','${x.id}')">刪除</button></div></div>`).join(''):'<div class="empty">還沒有地圖景點。</div>'}
function renderBudgets(){let total=data.budgets.reduce((s,x)=>s+(+x.money||0),0);$('totalMoney').textContent=total.toLocaleString();$('budgetList').innerHTML=data.budgets.length?data.budgets.map(x=>`<div class="item"><div class="item-title">${x.name}</div><div class="muted">${x.date||''}</div><div>NT$ / VND：${(+x.money||0).toLocaleString()}</div><div class="actions"><button class="danger" onclick="del('budgets','${x.id}')">刪除</button></div></div>`).join(''):'<div class="empty">還沒有花費紀錄。</div>'}
function renderPlaces(){ $('placeList').innerHTML=data.places.length?data.places.map(x=>`<div class="item"><div class="item-title">${x.done?'✅':'⬜'} ${x.name}</div><div class="muted">${x.note||''}</div><div class="actions"><button onclick="togglePlace('${x.id}')">完成/取消</button><button class="danger" onclick="del('places','${x.id}')">刪除</button></div></div>`).join(''):'<div class="empty">還沒有收藏景點。</div>'}
function showPage(id,el){document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));$(id).classList.add('active');document.querySelectorAll('.nav').forEach(n=>n.classList.remove('active')); if(el&&el.classList.contains('nav'))el.classList.add('active')}
function modal(title,body){$('modalTitle').textContent=title;$('modalBody').innerHTML=body;$('modal').classList.remove('hidden')}
function closeModal(){$('modal').classList.add('hidden')}
function id(){return Date.now().toString(36)}
function openSettings(){modal('設定主標題',`<label>主標題</label><input id="mTitle" value="${data.title}"><label>副標題</label><input id="mSub" value="${data.subtitle}"><div class="form-actions"><button onclick="data.title=$('mTitle').value||'我的旅行';data.subtitle=$('mSub').value||'';closeModal();save()">儲存</button></div>`)}
function openScheduleForm(){modal('新增今日行程',`<label>時間</label><input id="fTime" type="time"><label>行程名稱</label><input id="fTitle" placeholder="例如：紅教堂"><label>地點</label><input id="fPlace" placeholder="例如：胡志明市"><label>備註</label><textarea id="fNote"></textarea><div class="form-actions"><button onclick="data.schedules.push({id:id(),day:state.day,time:$('fTime').value,title:$('fTitle').value||'未命名行程',place:$('fPlace').value,note:$('fNote').value});closeModal();save()">新增</button></div>`)}
function openMapForm(){modal('新增地圖景點',`<label>景點名稱</label><input id="mapName" placeholder="例如：Ben Thanh Market"><label>備註</label><textarea id="mapNote"></textarea><div class="form-actions"><button onclick="data.maps.push({id:id(),name:$('mapName').value||'未命名景點',note:$('mapNote').value});closeModal();save()">新增</button></div>`)}
function openBudgetForm(){modal('新增花費',`<label>日期</label><input id="bDate" type="date" value="${dayDate(state.day)}"><label>項目</label><input id="bName" placeholder="例如：Grab / 河粉"><label>金額</label><input id="bMoney" type="number" placeholder="例如：150000"><div class="form-actions"><button onclick="data.budgets.push({id:id(),date:$('bDate').value,name:$('bName').value||'未命名花費',money:$('bMoney').value});closeModal();save()">新增</button></div>`)}
function openPlaceForm(){modal('新增收藏景點',`<label>景點名稱</label><input id="pName" placeholder="例如：富國大世界"><label>備註</label><textarea id="pNote"></textarea><div class="form-actions"><button onclick="data.places.push({id:id(),name:$('pName').value||'未命名景點',note:$('pNote').value,done:false});closeModal();save()">新增</button></div>`)}
function del(type,itemId){data[type]=data[type].filter(x=>x.id!==itemId);save()}
function togglePlace(itemId){let p=data.places.find(x=>x.id===itemId);if(p)p.done=!p.done;save()}
init();
